apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
data:
  MONGO_URI: {{ .Values.config.mongoUri | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  AWS_S3_BUCKET: {{ .Values.config.awsS3Bucket | quote }}
  CLIENT_URLS: {{ .Values.config.clientUrls | quote }}
