{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-frontend
  annotations:
    alb.ingress.kubernetes.io/group.name: streamingapp
    alb.ingress.kubernetes.io/group.order: "100"
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-auth
  annotations:
    alb.ingress.kubernetes.io/group.name: streamingapp
    alb.ingress.kubernetes.io/group.order: "30"
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-backends
  annotations:
    alb.ingress.kubernetes.io/group.name: streamingapp
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/streaming
            pathType: Prefix
            backend:
              service:
                name: streaming
                port:
                  number: 3002
          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 3003
          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 3004
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 3004

{{- end }}
